apiVersion: v1
kind: Service
metadata:
  name: myweb-service
  namespace: myweb
spec:
  selector:
    app: myweb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

