apiVersion: v1
kind: PersistentVolume
metadata:
  name: myweb-pv
  namespace: myweb
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/myweb

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myweb-pvc
  namespace: myweb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector: 
    matchLabels:
      app: myweb  # PV의 라벨과 일치해야 함

